// @flow

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

/* globals */
export const RECEIVE_ME = 'RECEIVE_ME';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USERS = 'SET_USERS';

/* modals */
export const SET_MODAL_DATA = 'SET_MODAL_DATA';

/* questionnaires */
// export const SET_QUESTIONNAIRES = 'SET_QUESTIONNAIRES';
// export const UPDATE_QUESTIONNAIRE = 'UPDATE_QUESTIONNAIRE';
// export const ADD_QUESTIONNAIRE = 'ADD_QUESTIONNAIRE';
// export const SET_QUESTIONNAIRE = 'SET_QUESTIONNAIRE';
// export const SET_QUESTION_RESPONSES = 'SET_QUESTION_RESPONSES';
// export const SET_QUESTIONNAIRE_ASSIGNMENTS_FOR_USER = 'SET_QUESTIONNAIRE_ASSIGNMENTS_FOR_USER';
// export const SET_QUESTIONNAIRE_ASSIGNMENTS_FOR_QUESTIONNAIRE = 'SET_QUESTIONNAIRE_ASSIGNMENTS_FOR_QUESTIONNAIRE';
//
// /* questions */
// export const SET_QUESTIONS = 'SET_QUESTIONS';
// export const SET_QUESTION = 'SET_QUESTION';
// export const UPDATE_QUESTION = 'UPDATE_QUESTION';
//
// /* organizations */
// export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
// export const ADD_ORGANIZATION = 'ADD_ORGANIZATION';
// export const SET_ORGANIZATION = 'SET_ORGANIZATION';
// export const SET_ORGANIZATIONS = 'SET_ORGANIZATIONS';
// export const SET_ORGANIZATION_ASSIGNMENTS_FOR_USER = 'SET_ORGANIZATION_ASSIGNMENTS_FOR_USER';
