# Generated by Django 3.2.4 on 2021-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='city_state_zip',
        ),
        migrations.AddField(
            model_name='proposal',
            name='city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='zip',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
