# Generated by Django 3.2.4 on 2021-06-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20210628_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProposalLineCategory',
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
