# Generated by Django 3.2.4 on 2021-06-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('customer_name', models.CharField(blank=True, default=models.CharField(max_length=60), max_length=60)),
                ('technician_name', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=120)),
                ('city_state_zip', models.CharField(blank=True, max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('technician_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Proposal Line Categories',
            },
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(default=1.0)),
                ('um', models.CharField(choices=[('EA', 'EA'), ('FT', 'FT')], default='EA', max_length=2)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposallinecategory')),
            ],
            options={
                'verbose_name_plural': 'Proposal Line Items',
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('override', models.FloatField(blank=True, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposal')),
                ('proposal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposallineitem')),
            ],
            options={
                'verbose_name_plural': 'Proposal Lines',
            },
        ),
    ]
