# Generated by Django 3.2.4 on 2021-06-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalLineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Proposal Line Categories',
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0)),
                ('override', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposallinecategory')),
            ],
            options={
                'verbose_name_plural': 'Proposal Lines',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=60)),
                ('proposal_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposalline')),
            ],
        ),
    ]
