# Generated by Django 3.2.4 on 2021-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plupro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_line',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_line',
            field=models.ManyToManyField(null=True, to='plupro.ProposalLine'),
        ),
    ]
