# Generated by Django 3.2.4 on 2021-06-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plupro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposallineitem',
            name='category',
        ),
    ]
