# Generated by Django 3.2.4 on 2021-06-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plupro', '0002_alter_proposal_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalline',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalline',
            name='proposal_item',
        ),
        migrations.RemoveField(
            model_name='proposallineitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='ProposalLine',
        ),
        migrations.DeleteModel(
            name='ProposalLineCategory',
        ),
        migrations.DeleteModel(
            name='ProposalLineItem',
        ),
    ]
