# Generated by Django 3.2.4 on 2021-06-04 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plupro', '0002_remove_proposallineitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalline',
            name='category',
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposallinecategory'),
        ),
    ]
