# Generated by Django 3.2.4 on 2021-06-04 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plupro', '0002_auto_20210604_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_line',
        ),
        migrations.AddField(
            model_name='proposalline',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plupro.proposal'),
        ),
    ]
